name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: ["*"]
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  PYTHONUNBUFFERED: "1"
  PIP_DISABLE_PIP_VERSION_CHECK: "1"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.8.1
        with:
          pixi-version: v0.24.2
          cache: true
          environments: build
      - run: pixi run -e build build
      - uses: actions/upload-artifact@v4
        with:
          name: ipfr-${{ github.run_number }}-dist
          path: ./dist

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.8.1
        with:
          pixi-version: v0.24.2
          cache: true
          environments: >-
            build
            lint
      - run: pixi run lint

  docs:
    name: docs
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.8.1
        with:
          pixi-version: v0.24.2
          cache: true
          environments: >-
            build
            docs
      - uses: actions/download-artifact@v4
        with:
          name: ipfr-${{ github.run_number }}-dist
          path: ./dist
      - run: pixi run -e docs docs-lite
      - run: pixi run -e docs docs-sphinx
      - uses: actions/upload-artifact@v4
        with:
          name: ipfr-docs-${{ github.run_number }}
          path: ./build/docs
